### ISSUE TITLE
Request New Feature

### ISSUE THREAD

**Issue by anasrar** [anasrar/NihLink-Safelink-Template-Blogger#1]
Just Leave It Here

**Comment by AXnael** [comment]
#Request
Tambahin toggle baru (Countdown Timer) di bawah toggle random post.
Biar pengguna bisa atur mau pakai timer / enggak di tiap linknya.

**Comment by hacker781** [comment]
settingnya

Pada tanggal Sel, 9 Apr 2019 21.33 AXnael <notifications@github.com menulis:

**Comment by anasrar** [comment]
Done, Check Release v2.5.4

**Comment by AXnael** [comment]
#ASK
Kalau misalnya ditambahin fitur auto convert dari link safelink ke bitly bagus ga ya?

**Comment by anasrar** [comment]
# 🤷‍♂️🤷‍♂️

**Comment by risest** [comment]
Bang ansarar, di tambah dong safelink nya biar auto jadi 2 Page

**Comment by anasrar** [comment]
> Bang ansarar, di tambah dong safelink nya biar auto jadi 2 Page

maksudnya gimana ??
mau di buat random pagenya ??

**Comment by anasrar** [comment]
jadi page: ['p/page.html', 'p/page2.html','p/page3.html']

**Comment by risest** [comment]
@anasrar jadi gini pak Web - safelink1 - safelink 2 - tujuan

Safelink 1 dan 2 sama gpp yg penting ada 2 lah
