### ISSUE TITLE
bagaimana cara membuatnya

### ISSUE THREAD

**Issue by risest** [anasrar/NihLink-Safelink-Template-Blogger#4]
Saya sudah memasang template nya,dan membuat halaman dengan code <div id='output'></div>
Tapi masih error page.

apa yang kurang ya?? apakah file autogeneres.js dipasang dan dimn pasangnya??

**Comment by anasrar** [comment]
# Untuk Settingnya Di
Layout > page-setting > setting

```autogenerate.js``` itu bukan untuk page safelink
dokumentasi akan di perbarui
